channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4
  - altair_saver
  - ipywidgets=7.5
  - jupyterlab=2.1.3
  - matplotlib-base=3.2
  - nodejs
  - numba=0.48
  - pandas=1
  - pandas-profiling
  - pip
  - pillow
  - python=3.7
  - scipy=1.4