channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4
  - altair_saver
  - ipywidgets
  - jupyterlab
  - matplotlib-base
  - nodejs
  - numpy
  - pandas
  - pandas-profiling
  - pip
  - pillow
  - python=3.7
  - scipy=1.4