channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4
  - altair_saver
  - ipywidgets = 7.5.1
  - jupyterlab = 2.1.3
  - matplotlib-base = 3.2.2
  - nodejs = 15.2.1
  - numpy = 1.19.1
  - pandas = 1.1.1
  - pandas-profiling = 2.9.1
  - pip
  - pillow
  - python=3.7
  - scipy=1.4